### ISSUE TITLE
[BUG] Timeout while connecting to root process

### ISSUE THREAD

**Issue by TheEvilSkeleton** [zhanghai/MaterialFiles#211]
Greetings,
When using root, I am not able to use the app properly. It doesn't let me access to the internal storage or the root storage. Using Android 10 (API level 29)
![Screenshot_20191212-195926_Material_Files](https://user-images.githubusercontent.com/50847364/70761550-8f140d80-1d1b-11ea-871d-0445cdfde8a1.png)

**Comment by zhanghai** [comment]
What is your device model? Can you attach some log or bugreport?

**Comment by soredake** [comment]
I have this problem with root (after going to subdirectories) and sdcard (when trying to delete a file).

**Comment by TheEvilSkeleton** [comment]
> What is your device model? Can you attach some log or bugreport?

My device is the Lenovo P2; using a [custom ROM](https://forum.xda-developers.com/lenovo-p2/development/rom-havoc-os-v2-4-t3918141). How do I attach logs? Sorry, I have never done this.

**Comment by zhanghai** [comment]
Are you using supersu or magisk?

To send a bugreport, I'd recommend reboot your device, trigger the bug once or twice, and run `adb bugreport` which will generate a zip file in your current directory. Beware there might be personal info logged by careless apps so maybe you can just send the logcat txt file in the zip here, and maybe skim through it before upload.

**Comment by TheEvilSkeleton** [comment]
> Are you using supersu or magisk?

I'm using Magisk.

> To send a bugreport, I'd recommend reboot your device, trigger the bug once or twice, and run adb bugreport which will generate a zip file in your current directory. Beware there might be personal info logged by careless apps so maybe you can just send the logcat txt file in the zip here, and maybe skim through it before upload.

Do you know where I can remove all my personal info? I want to make sure that there isn't any of my information so I can send the txt file without being worried.

**Comment by zhanghai** [comment]
Maybe run `adb logcat -c` to clear previous log, trigger the bug, run  `adb logcat >log.txt` to get the log as a text file? This way it should contains less lines and you can manually check before sending.

**Comment by TheEvilSkeleton** [comment]
> Maybe run adb logcat -c to clear previous log, trigger the bug, run adb logcat >log.txt to get the log as a text file? This way it should contains less lines and you can manually check before sending.

Alright, I have followed the steps and it seems like everything worked well. [log.txt](https://github.com/zhanghai/MaterialFiles/files/3981718/log.txt)

**Comment by zhanghai** [comment]
I inspected the log and here is the related section, from starting an activity inside Magisk (for granting root access?) till the time out exception is thrown in Material Files.

Just to make sure, did you actually see the Magisk dialog (although log says a Magisk activity is launched, but it's possible to finish immediately without being visible), and clicked "Grant" on it? Is there any possibility there was a silent denial?

The time between them is also 10 seconds which looks correct according to [code](https://github.com/zhanghai/MaterialFiles/blob/6902b69f1b5ac052ee90495af659868266c49fd0/app/src/main/java/me/zhanghai/android/files/provider/root/RootFileService.java#L38). There isn't any log that should have been there if app code in root process is reached, so I suppose the root process isn't started anyway. There are some SELinux denial printed, but it is after the timeout exception, before which the root process already failed to start, so I assume they are not related. Sorry but this is all I could extract from the log, and I couldn't locate the bug from it 😥

```
12-18 23:20:26.840  1425  3840 I ActivityTaskManager: START u0 {act=log flg=0x18000020 cmp=com.topjohnwu.magisk/a.m (has extras)} from uid 0
12-18 23:20:26.847   608   659 E ANDR-PERF-OPTSHANDLER: Sched boost lock is already acquired. Concurrency not supported for this resource
12-18 23:20:26.847   608   659 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [3, 0]
12-18 23:20:26.850  8477  8477 D AndroidRuntime: Shutting down VM
12-18 23:20:26.854  7875  7875 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8dec91f
12-18 23:20:28.283  1955  3462 I DPMJ    : |REQ:RCVR| DPM creating socket
12-18 23:20:28.927   608   659 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-18 23:20:28.929  1425  1743 W NotificationService: Toast already killed. pkg=com.topjohnwu.magisk callback=android.app.ITransientNotification$Stub$Proxy@7605e9e
12-18 23:20:30.471  1425  1572 W WindowManager: Unable to start animation, surface is null or no children.
12-18 23:20:29.706   608   659 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
12-18 23:20:31.858  5290  5411 W Device  : Ignoring packet with type kdeconnect.notification because no plugin can handle it
12-18 23:20:32.287  1955  3462 I DPMJ    : |REQ:RCVR| DPM creating socket
12-18 23:20:36.288  1955  3462 I DPMJ    : |REQ:RCVR| DPM creating socket
12-18 23:20:36.359  8440  8466 W System.err: me.zhanghai.android.files.provider.remote.RemoteFileSystemException: java.util.concurrent.TimeoutException: Timeout while connecting to root process
12-18 23:20:36.360  8440  8466 W System.err: 	at h.a.a.c.m.g.i0.b(:3)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.i0.c(:2)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.c.a(Unknown Source:0)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.f.v.b(Unknown Source:9)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.k0.a(:2)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.e.a(Unknown Source:2)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.f.v.b(Unknown Source:9)
12-18 23:20:36.361  8440  8466 W System.err: 	at me.zhanghai.android.files.provider.remote.RemoteFileSystemProvider.a(Unknown Source:12)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.q0.a(Unknown Source:50)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.r.a(Unknown Source:8)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.p0.a(Unknown Source:34)
12-18 23:20:36.361  8440  8466 W System.err: 	at h.a.a.c.m.g.q0.a(:13)
12-18 23:20:36.362  8440  8466 W System.err: 	at h.a.a.c.h.q2.a(:1)
12-18 23:20:36.362  8440  8466 W System.err: 	at h.a.a.c.h.d1.run(Unknown Source:6)
12-18 23:20:36.362  8440  8466 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-18 23:20:36.362  8440  8466 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-18 23:20:36.362  8440  8466 W System.err: 	at java.lang.Thread.run(Thread.java:919)
12-18 23:20:36.362  8440  8466 W System.err: Caused by: java.util.concurrent.TimeoutException: Timeout while connecting to root process
12-18 23:20:36.362  8440  8466 W System.err: 	... 17 more
12-18 23:20:36.377  8440  8440 W me.zhanghai.android.files: type=1400 audit(0.0:78854): avc: denied { getattr } for comm=4173796E635461736B202331 path="/system/lib64/bootstrap" dev="mmcblk0p54" ino=2417 scontext=u:r:untrusted_app:s0:c167,c256,c512,c768 tcontext=u:object_r:system_bootstrap_lib_file:s0 tclass=dir permissive=0
12-18 23:20:36.380  8440  8440 W me.zhanghai.android.files: type=1400 audit(0.0:78855): avc: denied { getattr } for comm=4173796E635461736B202331 path="/vendor/lib64/android.hardware.camera.provider@2.4-external.so" dev="mmcblk0p55" ino=892 scontext=u:r:untrusted_app:s0:c167,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
12-18 23:20:36.380  8440  8440 W me.zhanghai.android.files: type=1400 audit(0.0:78856): avc: denied { getattr } for comm=4173796E635461736B202331 path="/vendor/lib64/android.hardware.camera.provider@2.4-legacy.so" dev="mmcblk0p55" ino=893 scontext=u:r:untrusted_app:s0:c167,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
12-18 23:20:36.380  8440  8440 W me.zhanghai.android.files: type=1400 audit(0.0:78857): avc: denied { getattr } for comm=4173796E635461736B202331 path="/vendor/lib64/camera.device@1.0-impl.so" dev="mmcblk0p55" ino=894 scontext=u:r:untrusted_app:s0:c167,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
12-18 23:20:36.380  8440  8440 W me.zhanghai.android.files: type=1400 audit(0.0:78858): avc: denied { getattr } for comm=4173796E635461736B202331 path="/vendor/lib64/camera.device@3.2-impl.so" dev="mmcblk0p55" ino=895 scontext=u:r:untrusted_app:s0:c167,c256,c512,c768 tcontext=u:object_r:vendor_file:s0 tclass=file permissive=0
```

**Comment by TheEvilSkeleton** [comment]
> Just to make sure, did you actually see the Magisk dialog (although log says a Magisk activity is launched, but it's possible to finish immediately without being visible), and clicked "Grant" on it? Is there any possibility there was a silent denial?

Yes. I also went in Magisk and disable root for this app and reenabled it.

> so I suppose the root process isn't started anyway. 

That's weird. All the other apps work well with Magisk.

> Sorry but this is all I could extract from the log, and I couldn't locate the bug from it disappointed_relieved

Ouch, don't worry; it's fine.

**Comment by sijad** [comment]
same issue here, my android version is 10

**Comment by soredake** [comment]
Log from android 10, crdroid 6.2.
[timeout_log.txt](https://github.com/zhanghai/MaterialFiles/files/4123471/timeout_log.txt)

**Comment by zhanghai** [comment]
Seems this line is critical:

```
01-28 18:34:51.758 16034 16034 I me.zhanghai.android.files: type=1400 audit(0.0:1406): avc: denied { getattr } for comm=4173796E635461736B202331 path="/system/lib64/bootstrap" dev="mmcblk0p61" ino=2546 scontext=u:r:untrusted_app:s0:c48,c257,c512,c768 tcontext=u:object_r:system_bootstrap_lib_file:s0 tclass=dir permissive=1 app=me.zhanghai.android.files
```

And Chainfire/librootjava#4 might fix this. Will upgrade `librootjava` to `1.3.0`.

**Comment by zhanghai** [comment]
Might have been fixed in 753b07d.

**Comment by TheEvilSkeleton** [comment]
I haven't received any updates

**Comment by Noctfield** [comment]
Hello,
I'm from the F-Droid version 1.0.1, but after reinstalling 1.0.2 released here, the same still happens. The device is an OnePlus 7T, 10.0.7.HD65, rooted w/ Magisk 20.3(20300), app root access granted "always".

**Comment by TheEvilSkeleton** [comment]
> Hello,
> I'm from the F-Droid version 1.0.1, but after reinstalling 1.0.2 released here, the same still happens. The device is an OnePlus 7T, stock 10.0.7.HD65, rooted w/ Magisk 20.3(20300), app root access granted "always".

Yes. I just installed 1.0.2 from F-Droid and it is still not working for me. @zhanghai I can send you an error log again if you want.

**Comment by TheEvilSkeleton** [comment]
Seems to be working now, thank you for fixing it. @zhanghai
